/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bitoo
 */
import static java.lang.Class.forName;
import java.sql.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.scene.control.DatePicker;
import javafx.scene.control.TextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
public class crreatenew extends javax.swing.JFrame {

    /**
     * Creates new form crreatenew
     */
    PreparedStatement pstmt;
 Statement stmt;
  Connection con;
    /**
     * Creates new form create
     */
    
        
        
        
    public crreatenew() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ACC_NO = new javax.swing.JTextField();
        NAME = new javax.swing.JTextField();
        PIN = new javax.swing.JTextField();
        MOBILE = new javax.swing.JTextField();
        PAN_NO = new javax.swing.JTextField();
        ADHAR_NO = new javax.swing.JTextField();
        BALANCE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ADDRESS = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        an = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        pin = new javax.swing.JLabel();
        geneder = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        pan = new javax.swing.JLabel();
        adhar = new javax.swing.JLabel();
        bal = new javax.swing.JLabel();
        DOB = new com.toedter.calendar.JDateChooser();
        ai = new javax.swing.JButton();
        ACC_TYPE = new javax.swing.JComboBox<>();
        GENDER = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Maharashatra Bank");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 20, 540, 52);

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("NEW ACCOUNT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(86, 109, 273, 32);

        jLabel3.setBackground(new java.awt.Color(51, 204, 255));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("ACC_NO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(22, 170, 124, 32);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("ACC_TYPE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 279, 130, 42);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("NAME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(22, 348, 96, 38);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(22, 451, 116, 54);

        jLabel7.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("PIN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(31, 580, 60, 50);

        jLabel8.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setText("GENDER");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(22, 708, 120, 44);

        jLabel9.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 255));
        jLabel9.setText("DOB");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(942, 145, 91, 66);

        jLabel10.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 255));
        jLabel10.setText("MOBILE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(942, 243, 100, 43);

        jLabel11.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setText("PAN_NO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(922, 331, 110, 43);

        jLabel12.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 255));
        jLabel12.setText("ADHAR_NO");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(908, 439, 150, 45);

        jLabel13.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 255));
        jLabel13.setText("BALANCE");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(930, 557, 130, 46);

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("CREATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(188, 828, 103, 31);

        jButton2.setBackground(new java.awt.Color(0, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(393, 828, 81, 31);

        ACC_NO.setBackground(new java.awt.Color(204, 204, 255));
        ACC_NO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ACC_NOKeyReleased(evt);
            }
        });
        getContentPane().add(ACC_NO);
        ACC_NO.setBounds(188, 170, 97, 32);

        NAME.setBackground(new java.awt.Color(204, 204, 255));
        NAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NAMEKeyReleased(evt);
            }
        });
        getContentPane().add(NAME);
        NAME.setBounds(216, 349, 132, 41);

        PIN.setBackground(new java.awt.Color(204, 204, 255));
        PIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PINKeyReleased(evt);
            }
        });
        getContentPane().add(PIN);
        PIN.setBounds(216, 582, 132, 50);

        MOBILE.setBackground(new java.awt.Color(204, 204, 255));
        MOBILE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MOBILEKeyReleased(evt);
            }
        });
        getContentPane().add(MOBILE);
        MOBILE.setBounds(1163, 224, 119, 45);

        PAN_NO.setBackground(new java.awt.Color(204, 204, 255));
        PAN_NO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PAN_NOKeyReleased(evt);
            }
        });
        getContentPane().add(PAN_NO);
        PAN_NO.setBounds(1163, 333, 119, 42);

        ADHAR_NO.setBackground(new java.awt.Color(204, 204, 255));
        ADHAR_NO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ADHAR_NOKeyReleased(evt);
            }
        });
        getContentPane().add(ADHAR_NO);
        ADHAR_NO.setBounds(1163, 429, 119, 43);

        BALANCE.setBackground(new java.awt.Color(204, 204, 255));
        BALANCE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BALANCEKeyReleased(evt);
            }
        });
        getContentPane().add(BALANCE);
        BALANCE.setBounds(1163, 559, 127, 46);

        ADDRESS.setBackground(new java.awt.Color(204, 204, 255));
        ADDRESS.setColumns(20);
        ADDRESS.setRows(5);
        ADDRESS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ADDRESSKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(ADDRESS);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(216, 437, 166, 96);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(616, 279, 74, 42);

        an.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anKeyReleased(evt);
            }
        });
        getContentPane().add(an);
        an.setBounds(429, 170, 132, 27);
        getContentPane().add(name);
        name.setBounds(397, 348, 162, 41);
        getContentPane().add(add);
        add.setBounds(403, 448, 152, 45);
        getContentPane().add(pin);
        pin.setBounds(403, 573, 130, 50);
        getContentPane().add(geneder);
        geneder.setBounds(465, 699, 131, 44);
        getContentPane().add(dob);
        dob.setBounds(682, 145, 148, 42);
        getContentPane().add(mobile);
        mobile.setBounds(676, 243, 166, 43);
        getContentPane().add(pan);
        pan.setBounds(676, 325, 149, 42);
        getContentPane().add(adhar);
        adhar.setBounds(676, 423, 96, 45);
        getContentPane().add(bal);
        bal.setBounds(676, 541, 108, 58);

        DOB.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(DOB);
        DOB.setBounds(1163, 165, 119, 30);

        ai.setBackground(new java.awt.Color(51, 255, 51));
        ai.setText("GET");
        ai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiActionPerformed(evt);
            }
        });
        getContentPane().add(ai);
        ai.setBounds(303, 174, 55, 25);

        ACC_TYPE.setBackground(new java.awt.Color(0, 204, 204));
        ACC_TYPE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SAVING ", "CURRENT" }));
        getContentPane().add(ACC_TYPE);
        ACC_TYPE.setBounds(180, 280, 100, 22);

        GENDER.setBackground(new java.awt.Color(0, 204, 204));
        GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "TRANSGENDER" }));
        GENDER.setOpaque(false);
        GENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENDERActionPerformed(evt);
            }
        });
        getContentPane().add(GENDER);
        GENDER.setBounds(220, 720, 113, 22);

        jLabel15.setBackground(new java.awt.Color(204, 255, 204));
        jLabel15.setForeground(new java.awt.Color(153, 255, 153));
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-940, -100, 2750, 1280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
         
        // TODO add your handling code here:
//GEN-FIRST:event_jButton1ActionPerformed
       
 try
 {
     Class.forName("com.mysql.jdbc.Driver");
    //  Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank1","root","shraddhha");
   
        con=DriverManager.getConnection("jdbc:mysql://localhost/bank1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","");
       
       JOptionPane.showMessageDialog(null,"Connection Successful");
       String sql="insert into newaccount values(?,?,?,?,?,?,?,?,?,?,?)";
       PreparedStatement pstmt=con.prepareStatement(sql);
       pstmt.setString(1,ACC_NO.getText());
       
       String acti;
         acti = ACC_TYPE.getSelectedItem().toString();
         
         
        pstmt.setString(2,acti);
         pstmt.setString(3,NAME.getText()); 
         pstmt.setString(4,ADDRESS.getText());
          pstmt.setString(5,PIN.getText());
          String acti1;
         acti1 = GENDER.getSelectedItem().toString();
         pstmt.setString(6, acti1);
         
          
           
             pstmt.setString(7,MOBILE.getText());
              pstmt.setString(8,PAN_NO.getText());
               pstmt.setString(9,ADHAR_NO.getText());
                pstmt.setString(10,BALANCE.getText());
                 pstmt.setString(11,((JTextField)DOB.getDateEditor().getUiComponent()).getText());
                // pstmt.setString(11,DOB.getText());
                pstmt.executeUpdate();
             JOptionPane.showMessageDialog(null, "successfull insertion"); 
             con.close();
             
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }  // TODO add your
         
       
      
           
       
       
     
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void anKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anKeyReleased
        // TODO add your handling code here:
      
        
        
           
              
    }//GEN-LAST:event_anKeyReleased

    private void ACC_NOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ACC_NOKeyReleased
        // TODO add your handling code here:
      
        String PATTERN="^[0-9]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(ACC_NO.getText());
        if(!match.matches())
        {
            an.setText("accountno incorrect");
        }
        else
        {
            an.setText(null);
        }
           
             
    }//GEN-LAST:event_ACC_NOKeyReleased

    private void NAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NAMEKeyReleased
        // TODO add your handling code here:
                                   
        
         String PATTERN="^[a-zA-Z0-9]{0,30} [a-zA-z0-9]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(NAME.getText());
        if(!match.matches())
        {
            name.setText("naming is incorrect");
        }
        else
        {
            name.setText(null);
        }
                          
    }//GEN-LAST:event_NAMEKeyReleased

    private void ADDRESSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ADDRESSKeyReleased
        // TODO add your handling code here:
          
        /* String PATTERN="^[a-zA-Z0-9]{0,30} [a-zA-z0-9]{0,30} [a-zA-Z0-9]{0,30} [a-zA-z0-9]{0,3S$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(ADDRESS.getText());
        if(!match.matches())
        {
            add.setText("address is incorrect");
        }
        else
        {
            add.setText(null);
        }*/
    }//GEN-LAST:event_ADDRESSKeyReleased

    private void PINKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PINKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(PIN.getText());
        if(!match.matches())
        {
            pin.setText("pin is incorrect");
        }
        else
        {
            pin.setText(null);
        }
    }//GEN-LAST:event_PINKeyReleased

    private void PAN_NOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PAN_NOKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(PAN_NO.getText());
        if(!match.matches())
        {
            pan.setText("pan is incorrect");
        }
        else
        {
            pan.setText(null);
        }
    }//GEN-LAST:event_PAN_NOKeyReleased

    private void ADHAR_NOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ADHAR_NOKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(ADHAR_NO.getText());
        if(!match.matches())
        {
            adhar.setText("adhar is incorrect");
        }
        else
        {
            adhar.setText(null);
        }
    }//GEN-LAST:event_ADHAR_NOKeyReleased

    private void BALANCEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BALANCEKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(BALANCE.getText());
        if(!match.matches())
        {
            bal.setText("balance is incorrect");
        }
        else
        {
            bal.setText(null);
        }
    }//GEN-LAST:event_BALANCEKeyReleased

    private void MOBILEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MOBILEKeyReleased
        // TODO add your handling code here:
         String PATTERN="^[0-9]{0,10}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(MOBILE.getText());
        if(!match.matches())
        {
            mobile.setText("mobile no is incorrect");
        }
        else
        {
            mobile.setText(null);
        }
    }//GEN-LAST:event_MOBILEKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new home ().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiActionPerformed
        // TODO add your handling code here:
           String contain="1234567890";
        Random rnd=new Random();
        StringBuilder sb=new StringBuilder(6);
        for(int i=0;i<6;i++)
        {
            sb.append(contain.charAt((rnd.nextInt(contain.length()))));
            
        }
String random=sb.toString();
ACC_NO.setText(random);
    }//GEN-LAST:event_aiActionPerformed

    private void GENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENDERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GENDERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crreatenew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crreatenew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crreatenew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crreatenew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crreatenew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ACC_NO;
    private javax.swing.JComboBox<String> ACC_TYPE;
    private javax.swing.JTextArea ADDRESS;
    private javax.swing.JTextField ADHAR_NO;
    private javax.swing.JTextField BALANCE;
    private com.toedter.calendar.JDateChooser DOB;
    private javax.swing.JComboBox<String> GENDER;
    private javax.swing.JTextField MOBILE;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField PAN_NO;
    private javax.swing.JTextField PIN;
    private javax.swing.JLabel add;
    private javax.swing.JLabel adhar;
    private javax.swing.JButton ai;
    private javax.swing.JLabel an;
    private javax.swing.JLabel bal;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel geneder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pan;
    private javax.swing.JLabel pin;
    // End of variables declaration//GEN-END:variables
}
